if(EXISTS "/home/youssef_alfred/teamproject2026/CodeBROs---CSCE1102-Lab-Project/tests/all_tests[1]_tests.cmake")
  include("/home/youssef_alfred/teamproject2026/CodeBROs---CSCE1102-Lab-Project/tests/all_tests[1]_tests.cmake")
else()
  add_test(all_tests_NOT_BUILT all_tests_NOT_BUILT)
endif()
